# Lista = [Pregunta, opción 1, opción 2, opción 3, opción 4, posición de la correcta]

pregunta11 = ['¿Cuál es la capital de Perú?', 'Lima', 'Montevideo', 'Asunción', 'Quito', 1]
pregunta12 = ['¿Cuál es la capital de Ecuador?', 'Lima', 'Montevideo', 'Asunción', 'Quito', 4]
pregunta13 = ['¿Cuál es la capital de Uruguay?', 'Lima', 'Montevideo', 'Asunción', 'Quito', 2]
pregunta14 = ['¿Cuál es la capital de Paraguay?', 'Lima', 'Montevideo', 'Asunción', 'Quito', 3]
pregunta15 = ['¿Cuál es la capital de Chile?', 'Lima', 'Santiago', 'Asunción', 'Quito', 2]

pregunta21 = ['¿Cuál es la capital de España?', 'París', 'Madrid', 'Berlín', 'Londres', 2]
pregunta22 = ['¿Cuál es la capital de Francia?', 'París', 'Madrid', 'Berlín', 'Londres', 1]
pregunta23 = ['¿Cuál es la capital de Alemania?', 'París', 'Madrid', 'Berlín', 'Londres', 3]
pregunta24 = ['¿Cuál es la capital de Reino Unido?', 'París', 'Madrid', 'Berlín', 'Londres', 4]
pregunta25 = ['¿Cuál es la capital de Italia?', 'París', 'Roma', 'Berlín', 'Praga', 2]

pregunta31 = ['¿Cuál es la capital de Cuba?', 'La Habana', 'San Juan', 'San José', 'Tegucigalpa', 1]
pregunta32 = ['¿Cuál es la capital de Puerto Rico?', 'La Habana', 'San Juan', 'San José', 'Tegucigalpa', 2]
pregunta33 = ['¿Cuál es la capital de Costa Rica?', 'La Habana', 'San Juan', 'San José', 'Tegucigalpa', 3]
pregunta34 = ['¿Cuál es la capital de Honduras?', 'La Habana', 'San Juan', 'San José', 'Tegucigalpa', 4]
pregunta35 = ['¿Cuál es la capital de Nicaragua?', 'Managua', 'San Juan', 'San José', 'Tegucigalpa', 1]

pregunta41 = ['¿Cuál es la capital de Croacia?', 'Zagreb', 'Viena', 'Budapest', 'Bucarest', 1]
pregunta42 = ['¿Cuál es la capital de Austria?', 'Zagreb', 'Viena', 'Budapest', 'Bucarest', 2]
pregunta43 = ['¿Cuál es la capital de Hungría?', 'Zagreb', 'Viena', 'Budapest', 'Bucarest', 3]
pregunta44 = ['¿Cuál es la capital de Rumania?', 'Zagreb', 'Viena', 'Budapest', 'Bucarest', 1]
pregunta45 = ['¿Cuál es la capital de Bulgaria?', 'Zagreb', 'Viena', 'Sofía', 'Bucarest', 3]

pregunta51 = ['¿Cuál es la capital de Afganistán?', 'Kabul', 'Riad', 'Daca', 'Nicosia', 1]
pregunta52 = ['¿Cuál es la capital de Arabia Saudita?', 'Kabul', 'Riad', 'Daca', 'Nicosia', 2]
pregunta53 = ['¿Cuál es la capital de Bangladés?', 'Kabul', 'Riad', 'Daca', 'Nicosia', 3]
pregunta54 = ['¿Cuál es la capital de Chipre?', 'Kabul', 'Riad', 'Daca', 'Nicosia', 4]
pregunta55 = ['¿Cuál es la capital de Indonesia?', 'Kabul', 'Riad', 'Daca', 'Yakarta', 4]

# Lista = [categoría, pregunta 1, pregunta 2, pregunta 3, pregunta 4, pregunta 5, premio]
categoria1 = [1, pregunta11, pregunta12, pregunta13, pregunta14, pregunta15, 1000]
categoria2 = [2, pregunta21, pregunta22, pregunta23, pregunta24, pregunta25, 2000]
categoria3 = [3, pregunta31, pregunta32, pregunta33, pregunta34, pregunta35, 3000]
categoria4 = [4, pregunta41, pregunta42, pregunta43, pregunta44, pregunta45, 4000]
categoria5 = [5, pregunta51, pregunta52, pregunta53, pregunta54, pregunta55, 5000]

categorias =[categoria1, categoria2, categoria3, categoria4, categoria5]